<?
/**
 * PamConsult Web Development Framework
 *
 * Copyright (c) 2007-2012 PamConsult GmbH
 *
 * This library is free software; you can redistribute it
 * and/or modify it under the terms of the GNU Lesser General
 * Public License as published by the Free Software Foundation;
 * either version 3 of the License, or (at your option) any
 * later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library. If not, see <http://www.gnu.org/licenses/>
 *
 * @author PamConsult GmbH http://www.pamconsult.com <info@pamconsult.com>
 * @copyright 2007-2012 PamConsult GmbH
 * @license http://www.opensource.org/licenses/lgpl-license.php LGPL
 */
 
class UrlRoute extends System_Model
{
    function __construct(&$datasource=null)
	{
		global $CONFIG;

		if( !isset($CONFIG['model']['urlroute']) )
			$CONFIG['model']['urlroute'] = 'url_routes';

		if( $datasource == null )
			$datasource = model_datasource($CONFIG['routing']['datasource']);

		parent::__construct($datasource,array('id'));
	}

	public function GetSchemaDefinition()
	{
		$res  = '
		<table name="'.$this->_table.'">
			<desc>This table holds all defined URL routes</desc>

			<field name="id" type="I4">
				<KEY/><AUTOINCREMENT/><UNSIGNED/>
			</field>
			<field name="route" type="C" size="255">
				<UNIQUE/>
			</field>
			<field name="autogenerated" type="I1"/>
			<field name="controller" type="C" size="100"/>
			<field name="method" type="C" size="100"/>
		</table>';
		return $res;
	}
	
	function __wakeup(){ /* Just to skip warnings in Model class */ }
}

?>
